### ISSUE TITLE
About validation

### ISSUE THREAD

**Issue by aajour** [facg3/msn-app#15]
https://github.com/facg3/msn-app/blob/ff636b1e5f77a2741fb61ac92ad16102227f6d15/front-end/js/dom.js#L33

I like how you using the empty field validation :+1: , but I prefer not to use `JS alert` for many reasons
like It's annoying, stops the entire browser and needing extra action to do (click)

> Instead, highlight the erroneous fields/values, and print a message at the top, explaining that the highlighted fields need to be corrected before the user can continue.

**Comment by MahmoudMH** [comment]
humm , i know this shouldn't used , but anyway just to handle this problem ,,

but thanks @aajour
